name: Publish Quarto docs

on:
  workflow_dispatch:

  push:
    branches:
      - '**'

permissions:
  contents: write
  pages: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12"]

    steps:
      - uses: actions/checkout@v4

      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Run quartodoc
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: |
          cd docs
          uvx --python="../.venv/bin/python" quartodoc build --verbose
          uvx --python="../.venv/bin/python" quartodoc interlinks

      - name: Check if docs were built successfully
        run: |
          cd docs
          if [ -f "_quarto/index.html" ]; then
            echo "✅ Docs built successfully - index.html is present"
            ls -la _quarto/
          else
            echo "❌ Docs build failed - index.html not found"
            exit 1
          fi

      - name: NOOP - Skip GitHub Pages publish
        if: github.repository == 'xability/py-maidr'
        run: |
          echo "NOOP: Skipping GitHub Pages publish for testing"
          echo "Would normally publish to: https://xability.github.io/py-maidr"
