name: Publish Quarto docs

on:
  workflow_dispatch:

  push:
    branches:
      - main

permissions:
  contents: write
  pages: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install UV
        run: |
          # Install UV using the official installation script
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Setup UV environment
        run: |
          # Create and activate virtual environment
          uv venv .venv
          source .venv/bin/activate
          echo "VIRTUAL_ENV=$VIRTUAL_ENV" >> $GITHUB_ENV
          echo "$VIRTUAL_ENV/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: |
          # Install project and its dependencies with development extras
          uv pip install -e ".[dev]"
          # Ensure quartodoc is installed
          uv pip install "quartodoc>=0.7.5,<0.8"

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Run quartodoc
        run: |
          cd docs
          quartodoc build --verbose
          quartodoc interlinks

      - name: Render and Publish to GitHub Pages
        if: github.repository == 'xability/py-maidr'
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
          path: docs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          QUARTO_PYTHON: .venv/bin/python
