name: Semantic Release

on:
  push:
    branches:
      - '**'        # Run on all branches
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install and configure Poetry
        uses: snok/install-poetry@v1

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: poetry install

      - name: Show python-semantic-release version
        run: poetry run semantic-release --version

      - name: Semantic Release (update changelog and version)
        uses: python-semantic-release/publish-action@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          args: "--verbosity=DEBUG"

# No steps for PyPI or GitHub Release publishing are present.
